site_name: GeometricAI
site_description: GeometricAI Documentation Portal
site_url: https://mehmetyamac.github.io/GeometricAI/

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search

nav:
  - Home: index.md